async function fetchNutrientData(apiKey, foodQuery, partialDescription) {
	const baseUrl = "https://api.nal.usda.gov/fdc/v1/foods/search";
	const params = new URLSearchParams({
	  query: foodQuery,
	  dataType: 'Branded',
	  pageSize: 25,
	  pageNumber: 2,
	  sortBy: 'dataType.keyword',
	  sortOrder: 'asc',
	  brandOwner: 'Kar Nut Products Company',
	  api_key: apiKey
	});
}

async function getFoodData(api_key, params) {								//params is a key:value list
	/*
	const req = new XMLHttpRequest();
	const uri = "https://api.nal.usda.gov/fdc/v1/foods/search";
	req.open("GET", uri);									//open request
	paramstr = new URLSearchParams(params);
	reqstr = (uri.concat("?",`API_KEY=${api_key}`,"&",paramstr));				//process key:value list and send to server
	console.log(reqstr);									//the URI generated by this code can be correctly used when clicked in chromium but not otherwise
	//await promisedClick(document.addEventListener("click", null));			//wait for mouseclick in window
	req.send(reqstr);
	req.onload = () => {									//set up event listener (executes upon load)
		if (req.status == 200) {
			document.getElementById("output").innerHTML = req.response;		//spit out the response using DOM
		} 
		else {										//403 (Forbidden)
			console.log(`Error: ${req.status} \r\n ${req.response}`);		//spit out an error using the console
		}
	}; */
	const uri = "https://api.nal.usda.gov/fdc/v1/foods/search";
	paramstr = new URLSearchParams (params); 
	reqstr = uri.concat("?",`api_key=${api_key}`,"&",paramstr);
	console.log(reqstr);
	var response = await fetch(reqstr,{method:"GET"});
	results = await response.json();
	console.log(results);
	//select 1st entry by default 
	var carbs, fibre, sodium, sugars, fats, energy;
	var gi, gl;
	let serving = results.foods[0].servingSize / (results.foods[0].servingSizeUnit === "g" ? 1 : 250);	//account for the fact that some serving sizes are given in cups (Not very common)
	for (const nutrient of results.food[0].foodNutrients) {
		if (nutrient.nutrientName.includes("Carbohydrate")) {
			carbs = nutrient.value;									//this one is in grams
		}
		else if(nutrient.nutrientName.includes("lipid")) {
			fats = nutrient.value;									
		}
		else if(nutrient.nutrientName.includes("Fiber")) {
			fibre = nutrient.value;
		}
		else if(nutrient.nutrientName.includes("Na")) {
			sodium = nutrient.value/ 1000;							//mg -> grams
		}
		else if (nutrient.nutrientName.toLowerCase().includes("sugar")) {
			sugars = nutrient.value;							//grams
		}
		else if (nutrient.nutrientName.toLowerCase().includes("energy")) {
			energy = nutrient.value;
		}
	}
	gi = ((carbs - fibre)* 70 + (sugars)*30)/carbs;
	gl = (gi*carbs)/100;
    
//Need to select an entry from the provided JSON, extract its nutrient values, and store them as an object. 
}
let key = "ifCZAscHCiFT5kcgxyDgDv6KW3dHzgnUIsvvFP4W";

let parameter = {
	query: "wholemeal bread", 
	dataType: "Branded",
	pageSize: 1,
	pageNumber: 1,
	sortBy: "dataType.keyword",
	sortOrder: "asc",
};
getFoodData(key, parameter);


